SELECT 1 AS ID, 'Apples' AS PRODUCT_NAME, 4.5 AS UNIT_PRICE, 'Per lb' AS UNITS, TO_TIMESTAMP_NTZ('2022-09-11') FIVETRAN_SYNCED
UNION
SELECT 2 AS ID, 'Bananas' AS PRODUCT_NAME, 2.99 AS UNIT_PRICE, 'Per lb' AS UNITS, TO_TIMESTAMP_NTZ('2022-09-11') FIVETRAN_SYNCED
UNION
SELECT 3 AS ID, 'Avocados' AS PRODUCT_NAME, 3.99 AS UNIT_PRICE, 'Each' AS UNITS, TO_TIMESTAMP_NTZ('2022-09-12') FIVETRAN_SYNCED
UNION
SELECT 4 AS ID, 'Watermelon' AS PRODUCT_NAME, 9.99 AS UNIT_PRICE, 'Each' AS UNITS, TO_TIMESTAMP_NTZ('2022-09-12') FIVETRAN_SYNCED