
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'hakkoda_edw'
version: '1.3.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring tests
tests:
  +store_failures: true
  +schema: test_results

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  pre-hook: "{{ logging.log_model_start_event() }}"
  post-hook: "{{ logging.log_model_end_event() }}"
  hakkoda_edw:
    marts:
      core:
        +materialized: table       
    staging:
      +materialized: view
    raw_stage:
      +materialized: view
      +schema: 'raw_stage' 
    hash_stage:
      +materialized: view
      +schema: 'hash_stage'       
    raw_vault:
      +materialized: incremental 
      +schema: 'raw_vault'         
    etl_admin:
      +materialized: incremental      

vars:
  'dbt_date:time_zone': 'America/Los_Angeles'
  hubspot_database: fivetran
  hubspot_schema: hubspot
  is_incremental: true
  _fivetran_synced_local: 'CONVERT_TIMEZONE(''UTC'',''America/Los_Angeles'', _FIVETRAN_SYNCED)'
