{{ config(
    materialized='view'
    )    
}}

SELECT h.HUB_COMPANY_HKEY AS COMPANY_KEY 
,s.LOAD_DATETIME AS EFFECTIVE_DATETIME
,COMPANY_NAME 
,ID 
,PROPERTY_DESCRIPTION DESCRIPTION
,PROPERTY_NUMBEROFEMPLOYEES NUM_OF_EMPLOYEES
,PROPERTY_DOMAIN DOMAIN 
,PROPERTY_WEBSITE WEBSITE
,PROPERTY_LINKEDIN_COMPANY_PAGE LINKEDIN_PAGE
,PROPERTY_CITY CITY 
,PROPERTY_STATE STATE 
,PROPERTY_COUNTRY COUNTRY
,PROPERTY_TIMEZONE TIMEZONE
,PROPERTY_FOUNDED_YEAR YEAR_FOUNDED
,PROPERTY_INDUSTRY INDUSTRY 
FROM {{ref('hub_company')}} h 
INNER JOIN {{ref('sat_company_details_hubspot')}} s ON h.HUB_COMPANY_HKEY = s.HUB_COMPANY_HKEY 
QUALIFY ROW_NUMBER() OVER (PARTITION BY s.HUB_COMPANY_HKEY ORDER BY s.LOAD_DATETIME DESC) = 1
